# This is a basic workflow to help you get started with Actions

name: Deploy React app on AWS Elastic Beanstalk

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "deploy-react-beanstalk" ]
env:
    DEPLOY_PACKAGE: "${{ github.sha }}.zip"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Generate deployment package
        run: |
          zip -r ${{ env.DEPLOY_PACKAGE }} . -x '*.git*' -x '**node_modules**'
          mkdir -p "${{ github.workspace }}/mywebapp"
          cp ${{ env.DEPLOY_PACKAGE }} "${{ github.workspace }}/mywebapp/"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: "${{ github.workspace }}/mywebapp/"

      

